-- Active: 1730656127862@@127.0.0.1@5432@postgres@public
CREATE TABLE Genre (
    GenreID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(50) NOT NULL
);

CREATE TABLE Movie(
    MovieID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(100) NOT NULL,
    "Year" INT,
    GenreID INT,
    FOREIGN KEY (GenreID) REFERENCES Genre(GenreID)
);

CREATE TABLE Users(
    UserID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "Name" VARCHAR(100),
    "Username" VARCHAR(50) UNIQUE NOT NULL,
    "Password" VARCHAR(100) NOT NULL,
    BirthYear INT
);

CREATE TABLE Review(
    ReviewID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    UserID INT NOT NULL,
    MovieID INT NOT NULL,
    Stars INT CHECK (Stars >= 1 AND Stars <= 5),
    ReviewText TEXT,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE
);

CREATE TABLE Favorite (
    FavoriteID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    UserID INT NOT NULL,
    MovieID INT NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (MovieID) REFERENCES Movie(MovieID) ON DELETE CASCADE
);